### ISSUE TITLE
似乎这个package并没有指定UA？

### ISSUE THREAD

**Issue by LaoshuBaby** [DaydreamCafe/PyBangumi#1]
按照[bangumi的UA规范](https://github.com/bangumi/api/blob/c43d256a351e80c678a0e08a51ad6aa9d53a6aed/docs-raw/user%20agent.md)：

> 如果你的应用是一个开源项目，请在 User Agent 附上项目主页。
> 
> 各种请求库的默认 UA 可能会被禁用。
> 
> 建议的 User Agent 比如：
> 
> + czy0729/Bangumi/6.4.0 (Android) (http://github.com/czy0729/Bangumi): 移动端 APP，请添加版本号。
> + trim21/bangumi-episode-ics (https://github.com/Trim21/bangumi-episode-calendar)：cloudflare workers，不进行分发，不需要添加版本号。
> + sai/my-private-project：某人的私有项目。

~~或者说其实是我读代码能力低下，明明有写但没找到？~~

**Comment by WhitePaper233** [comment]
确实是没有遵守这个规范 但是最近忙于高考没啥时间继续开发和维护 等到高考后会把这个功能整上的

**Comment by LaoshuBaby** [comment]
> 但是最近忙于高考没啥时间继续开发和维护 等到高考后会把这个功能整上的

震惊（原来是高中生吗（最近要写毕业论文搞各个数据源的爬虫（在pypi看有没有现成的没有就造一个（发现了这个就不用造了

不介意的话我来点PR？

**Comment by WhitePaper233** [comment]
> > 但是最近忙于高考没啥时间继续开发和维护 等到高考后会把这个功能整上的
> 
> 震惊（原来是高中生吗（最近要写毕业论文搞各个数据源的爬虫（在pypi看有没有现成的没有就造一个（发现了这个就不用造了
> 
> 不介意的话我来点PR？

如果可以的话那非常感谢！
